name: Read Info.plist

on: 
  workflow_dispatch:

jobs:
  read-info-plist:
    runs-on: macos-latest
    steps:
      - name: Download DMG file
        run: |
          curl -L -o Brave-Browser.dmg https://laptop-updates.brave.com/latest/osx/Brave-Browser.dmg
          ls -l Brave-Browser.dmg

      - name: Create Mount Directory
        run: |
          mkdir -p ${{ github.workspace }}/mount

      - name: Mount DMG file
        run: |
          hdiutil attach -mountpoint ${{ github.workspace }}/mount Brave-Browser.dmg

      - name: List Contents of Mount Point
        run: |
          ls -lR ${{ github.workspace }}/mount > mount_contents.txt
          cat mount_contents.txt

      - name: List Contents of Contents Directory
        run: |
          ls -lR "${{ github.workspace }}/mount/Brave Browser.app/Contents" > contents_directory.txt
          cat contents_directory.txt

      - name: Extract CFBundleShortVersionString
        run: |
          INFO_PLIST_PATH="${{ github.workspace }}/mount/Brave Browser.app/Contents/Info.plist"
          if [ -f "$INFO_PLIST_PATH" ]; then
            echo "Extracting CFBundleShortVersionString from $INFO_PLIST_PATH"
            plutil -extract CFBundleShortVersionString xml1 -o - "$INFO_PLIST_PATH" | grep "<string>" | sed -e 's/<string>//' -e 's/<\/string>//'
          else
            echo "Info.plist not found at $INFO_PLIST_PATH"
          fi

      - name: Unmount DMG file
        run: |
          hdiutil detach ${{ github.workspace }}/mount

      - name: Cleanup
        run: |
          rm -f Brave-Browser.dmg
          rm -rf ${{ github.workspace }}/mount
